export const PRODUCT_REQUEST_START = 'PRODUCT_REQUEST_START';
export const PRODUCT_REQUEST_SUCCEEDED = 'PRODUCT_REQUEST_SUCCEEDED';
export const PRODUCT_REQUEST_FAILED = 'PRODUCT_REQUEST_FAILED';

export const PRODUCT_SAVE_START = 'PRODUCT_SAVE_START';
export const PRODUCT_SAVE_SUCCEEDED = 'PRODUCT_SAVE_SUCCEEDED';
export const PRODUCT_SAVE_SUCCEEDED_A_WHILE_AGO = 'PRODUCT_SAVE_SUCCEEDED_A_WHILE_AGO';
export const PRODUCT_SAVE_FAILED = 'PRODUCT_SAVE_FAILED';
